uwsgi:
  socket: /ns/runtime/sock/wsgi/hermes.sock
  module: apps.hermes.app.gateway:dispatch
  chmod: 775
  chown: appfactory
  uid: appfactory
  gid: runtime
  master: on
  cheaper: on
  processes: 2
  enable-threads: on
  threads: 40
  pcre-jit: on
  touch-reload: /ns/runtime/trigger/hermes.uwsgi
