uwsgi:
  app_id: hermes
  module: apps.hermes.app:APIServer
  hostname: api.amp.sh
  chdir: /ampush/apps/hermes/app
  include: /ampush/platform/conf/uwsgi/vassal.ini
  include: /ampush/platform/conf/uwsgi/runtime/python.ini
