uwsgi:
  chdir: /ampush/apps/hermes/app
  socket: /ns/runtime/sock/wsgi/hermes.sock
  module: apps.hermes.app:APIServer
  chmod: 775
  chown: appfactory
  uid: appfactory
  gid: runtime
  master: on
  cheaper: on
  processes: 2
  enable-threads: on
  threads: 40
  pcre-jit: on
  touch-reload: /ns/runtime/trigger/hermes.uwsgi
  tcp-fast-open: on
  pymodule-alias: app=/ampush/apps/hermes/app
  pythonpath: /ampush/apps/hermes
  pythonpath: /ampush/apps/hermes/app
  pythonpath: /ampush/apps/hermes/app/lib
  pythonpath: /ampush/apps/hermes/app/lib/dist
  post-buffering: on
