#!/bin/bash

## Generates autobuilt-files for Hermes.


echo "";
echo "";
echo "========= Hermes: Compilation Routine =========";
echo "";
echo "--- Building application JS...";
echo "";
echo "--- Building application SASS...";
echo "";
echo "--- Building application docs...";
echo "";
echo "--- Building API client libraries...";
echo "";
echo "(building Python bindings)...";
PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="/appengine:/appengine/lib:app:app/lib:app/lib/dist" python tools/gen_protorpc.py registry localhost:8080 /v1/rpc/tracker /_api/registry -d tools/client -f;
echo "";
echo "(building JS bindings)...";
echo "";
echo "(building Protobuf bindings)...";
echo ""
echo "Building API docs...";
echo "";
echo "========= Compilation succeeded. =========";
echo "";
echo "";
