#!/bin/bash

## Generates autobuilt-files for Hermes.

VERSION="0.5"
TRACK="dev"
BUILD="00"

RELEASE="$VERSION-$BUILD-$TRACK"

echo "";
echo "";
echo "========= Hermes: Compilation Routine =========";
echo "";
echo "--- Building application JS...";
echo "";
echo "--- Building application SASS...";
echo "";
echo "--- Building application docs...";
pushd app;
mv __init__.py __init__.py_;
PATH=/usr/local/bin:/usr/bin:/bin:/momentum:/tools:$PATH PYTHONPATH="app:app/lib:app/lib/dist:/appengine:/appengine/lib:/momentum:/tools" sphinx-apidoc -o ../docs/source/app -l -H "Hermes" -A "Ampush" -V "$VERSION" -R "$RELEASE" -d 3 ./;
mv __init__.py_ __init__.py;
popd;
PATH=/usr/local/bin:/usr/bin:/bin:/momentum:/tools:$PATH PYTHONPATH="app:app/lib:app/lib/dist:/appengine:/appengine/lib:/momentum:/tools" sphinx-build -b html docs/source/app docs/html/app;
echo "";
#echo "--- Building API client libraries...";
#echo "";
#echo "(building Python bindings)...";
#pushd app/;
#echo "Starting registry service on port 8080...";
#python main.py + 5 8080;
#sleep 1;
#popd;
#echo "Reading registry...";
#PYTHONDONTWRITEBYTECODE=1 PYTHONPATH="/appengine:/appengine/lib:app:app/lib:app/lib/dist" python tools/gen_protorpc.py registry localhost:8080 /v1/rpc/tracker /_api/registry -d tools/client -f;
#echo "";
#echo "(building JS bindings)...";
#echo "";
#echo "(building Protobuf bindings)...";
#echo ""
echo "Building API docs...";
PATH=/usr/local/bin:/usr/bin:/bin:/momentum:/tools:$PATH PYTHONPATH="app:tools:app/lib:app/lib/dist:/appengine:/appengine/lib:/momentum:/tools" sphinx-apidoc -o docs/source/api -l --full -H "Hermes API" -A "Ampush" -V "$VERSION" -R "$RELEASE" -d 2 ./tools/client;
PATH=/usr/local/bin:/usr/bin:/bin:/momentum:/tools:$PATH PYTHONPATH="app:tools:app/lib:app/lib/dist:/appengine:/appengine/lib:/momentum:/tools" sphinx-build -b html docs/source/api docs/html/api;
echo "";
echo "========= Compilation succeeded. =========";
echo "";
echo "";
